existence_dependence:
  '23iz_$XTT7Qh5EJtFtqs2X' : '0_LLnb76j0dvprA5TO6l_m'
  '1A2qVk78PCQRC$rtMC4SDY' : '1UH7XjeubFPe8ud33kpdAD'
  '3f0mhqOMzDdxWLQ6t25_Qw' : '2JXote8SH4wvyJ6o7XOlgR'
  '1s61g5XiL70eShhiNX3DwP' : '1I3q0zjCDDIA7XkWxylMx5'
variations: 
  '23iz_$XTT7Qh5EJtFtqs2X' : [[0.0,0.2,0.0],[[-0.0,-0.2,0.0]]]
  '1A2qVk78PCQRC$rtMC4SDY' : [[0.0,0.2,0.0],[[-0.0,-0.2,0.0]]]
  '3f0mhqOMzDdxWLQ6t25_Qw' : [[0.2,0.0,0.0],[[-0.2,-0.0,0.0]]]
  '1s61g5XiL70eShhiNX3DwP' : [[0.2,0.0,0.0],[[-0.2,-0.0,0.0]]]

current_time: 5.0

sensor_u : np.linspace(-np.pi,np.pi, 200)
sensor_v : np.array([0.0])
sensor_max_range : 10
sensor_std : 0.05
sensor_p0: 0.4
sensor_std_factor: 1.0

U_COV: np.diag([0.2, 0.1, 1e-25, np.radians(1)])**2

rbpf_N_particles: 10
rbpf_max_steps_to_resample: 10
rbpf_reservoir_decay_rate : 0.5

method_variation_names:
  0 : Simulation
  1 : BPFS
  2 : BPFS-t
  3 : BPFS-tg
  4 : logodds

movie: best_particlea