#construction (BIM complement)
IFC_PATH: '/home/alon18/repos/4dbimloc/bim4loc/binaries/arena.ifc'
existence_dependence:
  '23iz_$XTT7Qh5EJtFtqs2X' : '0_LLnb76j0dvprA5TO6l_m'
  '1A2qVk78PCQRC$rtMC4SDY' : '1UH7XjeubFPe8ud33kpdAD'
  '3f0mhqOMzDdxWLQ6t25_Qw' : '2JXote8SH4wvyJ6o7XOlgR'
  '1s61g5XiL70eShhiNX3DwP' : '1I3q0zjCDDIA7XkWxylMx5'
common_mistakes: 
  '23iz_$XTT7Qh5EJtFtqs2X' : [[0.0,0.2,0.0],[[-0.0,-0.2,0.0]]]
  '1A2qVk78PCQRC$rtMC4SDY' : [[0.0,0.2,0.0],[[-0.0,-0.2,0.0]]]
  '3f0mhqOMzDdxWLQ6t25_Qw' : [[0.2,0.0,0.0],[[-0.2,-0.0,0.0]]]
  '1s61g5XiL70eShhiNX3DwP' : [[0.2,0.0,0.0],[[-0.2,-0.0,0.0]]]
current_time: 5.0

#sensor and odom
sensor_u : np.linspace(-np.pi,np.pi, 300)
sensor_v : np.array([0.0])
sensor_max_range : 6.0
sensor_std : 0.05
sensor_p0: 0.4
sensor_std_factor: 1.0

DT: 1.0
velocity_factor: 1.0 #1.0 for slow, 2.0 for mid, 4.0 for fast. Use these so actions numbers are divisible
U_COV: velocity_factor * np.diag([0.1, 0.02, 1e-25, np.radians(0.5)])**2

#trajectory
straight: velocity_factor * np.array([0.25,0.0 ,0.0 ,0.0]) * DT
turn_left: velocity_factor * np.array([0.0 ,0.0 ,0.0, np.pi/16]) * DT
turn_right: velocity_factor * np.array([0.0, 0.0, 0.0, -np.pi/16]) * DT
actions : straight * int(18//velocity_factor)
          + turn_left * int(8//velocity_factor)
          + straight * int(16//velocity_factor)
          + turn_right * int(8//velocity_factor)
          + straight * int(40//velocity_factor)
          + turn_right * int(8//velocity_factor)
          + straight * int(8//velocity_factor)

#RBPF
rbpf_N_particles: 10
rbpf_max_steps_to_resample: 10
rbpf_reservoir_decay_rate : 0.5
rbpf_weight_calculation_method : "default" #"subdue_max_range" or "default"

#evaluation
method_variation_names:
  0 : Simulation
  1 : BPFS
  2 : BPFS-t
  3 : BPFS-tg
  4 : logodds
movie: "best_particle" #"best_particle" or "default" == expected
